### ISSUE TITLE
I think you forgot to push some code to github

### ISSUE THREAD

**Issue by matthiaz** [BvdP/Inkscape_helper#1]
In your other project you mention:

move Ellipse class to inkscape_helper
BvdP committed on 21 Dec 2015

modify ell_box to use Inkscape_helper
BvdP committed on 11 Dec 2015

But in inkscape_helper, nothing was changed at those times, and I can't seem to find the class Elipse in the innkscape_helper.

I'm guessing you did the work, but simply didn't push it to github :-)

**Comment by BvdP** [comment]
I think you may be right. Anyway, I have recently pushed to github so it should be up to date now :smiley:  . This has nothing to do with the elliptical box maker but it should not cause any problems (let me know if it does)
